export enum InputType {
  Text = 'text',
  Number = 'number',
  TextArea = 'textarea',
  Checkbox = 'checkbox',
  CheckboxGroup = 'checkbox-group',
  RadioGroup = 'radio-group',
  Slider = 'slider',
  SegmentedSlider = 'segmented-slider',
  Range = 'range',
  Select = 'select',
  Search = 'search',
  File = 'file',
  Image = 'image',
  CustomTextArea = 'custom-textarea',
  Subform = 'subform',
}
