name: Publish to Bit

on:
  push:
    branches:
      - master

jobs:
  tag-and-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto:')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies and build app
      - name: Install Dependencies
        run: npm install bit
      - name: Install bit-bin
        run: sudo npm install bit-bin@14.7.6 -g --unsafe-perm
      - name: bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit config
      - name: bit import
        run: |
          bit -v && bit import
      - name: bit export
        run: |
          bit status
          bit tag -a
          bit export
      - name: Commit changes
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .bitmap
          git commit -m "auto: update .bitmap with new component versions. "
          git push
